# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXR35Nu19cdyKxGA2v7vszJJKogvLdDT
"""

import numpy as np
import matplotlib.pyplot as plt

print("Enter 4 values for x1 (space-separated):")
x1 = list(map(float, input("x1: ").strip().split()))

print("Enter 4 values for x2 (space-separated):")
x2 = list(map(float, input("x2: ").strip().split()))

X = np.array([x1, x2])
labels = ['x1', 'x2']
print("\n📌 Original Data Matrix X:")
print(X)

X_mean = np.mean(X, axis=0)
X_centered = X - X_mean
print("\n📉 Mean-Centered Data:")
print(X_centered)

cov_matrix = np.cov(X_centered, rowvar=False)
print("\n📊 Covariance Matrix:")
print(cov_matrix)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\n🧮 Eigenvalues:")
print(eigenvalues)
print("\n🧭 Eigenvectors (columns):")
print(eigenvectors)

sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues_sorted = eigenvalues[sorted_indices]
eigenvectors_sorted = eigenvectors[:, sorted_indices]

X_transformed = X_centered @ eigenvectors_sorted
print("\n📈 Transformed Data (PCA projection):")
print(X_transformed)

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.scatter(X[:, 0], X[:, 1], color='blue', label='Original Data')
for i in range(len(X)):
    plt.text(X[i, 0]+0.02, X[i, 1]+0.02, labels[i], fontsize=9)
plt.title("📌 Original Data (First 2 Features)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.grid(True)
plt.axis('equal')

plt.subplot(1, 2, 2)
plt.scatter(X_transformed[:, 0], X_transformed[:, 1], color='green', label='PCA Projection')
for i in range(len(X_transformed)):
    plt.text(X_transformed[i, 0]+0.02, X_transformed[i, 1]+0.02, labels[i], fontsize=9)
plt.title("📈 Data in PCA Space (PC1 vs PC2)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.grid(True)
plt.axis('equal')

plt.tight_layout()
plt.show()