# -*- coding: utf-8 -*-
"""GANs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGenR0Hb7OpZLOqAdKPEXZjFUvwFm2wr
"""

import random
import matplotlib.pyplot as plt

def fitness(chromosome):
    a, b, c, d, e, f, g, h = chromosome
    return (a + b) - (c + d) + (e + f) - (g + h)

def input_population():
    print("Enter 4 individuals as 8-digit chromosome (digits separated by space):")
    population = []
    for i in range(4):
        while True:
            try:
                line = input(f"Individual {i+1}: ")
                genes = list(map(int, line.strip().split()))
                if len(genes) != 8 or any(g < 0 or g > 9 for g in genes):
                    raise ValueError
                population.append(genes)
                break
            except:
                print("Invalid input. Please enter 8 digits between 0-9.")
    return population

def evaluate_population(population):
    evaluated = [(chrom, fitness(chrom)) for chrom in population]
    evaluated.sort(key=lambda x: x[1], reverse=True)
    return evaluated

def crossover(parent1, parent2, point=4):
    child1 = parent1[:point] + parent2[point:]
    child2 = parent2[:point] + parent1[point:]
    return child1, child2

def mutate(chromosome, mutation_rate=0.1):
    mutated = chromosome[:]
    for i in range(len(mutated)):
        if random.random() < mutation_rate:
            mutated[i] = random.randint(0, 9)
    return mutated

population = input_population()

evaluated = evaluate_population(population)
print("\n📊 Fitness Evaluation:")
for i, (chrom, fit) in enumerate(evaluated):
    print(f"Individual {i+1}: {chrom} -> Fitness: {fit}")

print("\n🔀 Crossover:")
parent1, parent2 = evaluated[0][0], evaluated[1][0]
child1, child2 = crossover(parent1, parent2)
print(f"Parent 1: {parent1}")
print(f"Parent 2: {parent2}")
print(f"Child 1: {child1}")
print(f"Child 2: {child2}")

print("\n🧬 Mutation (10% chance per gene):")
mutated1 = mutate(child1)
mutated2 = mutate(child2)
print(f"Mutated Child 1: {mutated1}")
print(f"Mutated Child 2: {mutated2}")

all_individuals = evaluated + [(child1, fitness(child1)), (child2, fitness(child2)),
                               (mutated1, fitness(mutated1)), (mutated2, fitness(mutated2))]
max_fit = max(all_individuals, key=lambda x: x[1])
print(f"\n🏆 Maximum Fitness: {max_fit[1]} from Individual: {max_fit[0]}")

def run_genetic_algorithm(pop, generations=10):
    fitness_history = []

    for gen in range(generations):
        print(f"\n📊 Generation {gen + 1} Fitness Evaluation:")
        evaluated = evaluate_population(pop)

        for i, (chrom, fit) in enumerate(evaluated):
            print(f"Individual {i+1}: {chrom} -> Fitness: {fit}")

        best_fit = evaluated[0]
        print(f"✅ Best Fit in Gen {gen + 1}: {best_fit[0]} with Fitness = {best_fit[1]}")
        fitness_history.append(best_fit[1])

        # Select top 2 for crossover
        parent1, parent2 = evaluated[0][0], evaluated[1][0]
        child1, child2 = crossover(parent1, parent2)

        # Mutate children
        child1 = mutate(child1)
        child2 = mutate(child2)

        # Form new population: keep top 2 + 2 new children
        pop = [parent1, parent2, child1, child2]

    return fitness_history

fitness_progress = run_genetic_algorithm(population, generations=10)

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(fitness_progress)+1), fitness_progress, marker='o', linestyle='-', color='blue')
plt.title("📈 Fitness Progression Over Generations")
plt.xlabel("Generation")
plt.ylabel("Best Fitness")
plt.grid(True)
plt.tight_layout()
plt.show()