# -*- coding: utf-8 -*-
"""SOM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYQyFDgOJG7bdHq9EBsDjIBTJoGVUhza
"""

import numpy as np
import matplotlib.pyplot as plt

weights = np.array([
    [0.7, 0.9, 0.2, 0.1, 0.3],  # Cluster 0
    [0.3, 0.1, 0.2, 0.7, 0.8]   # Cluster 1
])

# Learning rate schedule
eta = 0.8
cycles = 4
history = [weights.copy()]

print("Enter 4 input vectors, 5 values each (space-separated):")
inputs = []
for i in range(4):
    while True:
        try:
            vec = list(map(float, input(f"Vector {i+1}: ").strip().split()))
            if len(vec) != 5:
                raise ValueError
            inputs.append(vec)
            break
        except:
            print("Invalid input. Please enter 5 space-separated numbers.")
inputs = np.array(inputs)

for epoch in range(cycles):
    print(f"\n📘 Epoch {epoch + 1}, Learning Rate η = {eta}")
    for idx, x in enumerate(inputs):
        # Calculate Euclidean distance to each cluster
        distances = np.linalg.norm(weights - x, axis=1)
        print(f"Input {idx+1}: {x}")
        print(f"Distances: Cluster 0 = {distances[0]:.4f}, Cluster 1 = {distances[1]:.4f}")
        # Update weights of the winning cluster
        winner = np.argmin(distances)
        print(f"Winner: Cluster {winner}")
        weights[winner] += eta * (x - weights[winner])
        print(f"Input {idx+1} assigned to Cluster {winner}. Updated Weights:")
        print(f"Cluster 0: {weights[0]}")
        print(f"Cluster 1: {weights[1]}")

    eta /= 2  # decay learning rate
    history.append(weights.copy())

# Final clustering
print("\n✅ Final Assignment of Inputs:")
for idx, x in enumerate(inputs):
    distances = np.linalg.norm(weights - x, axis=1)
    winner = np.argmin(distances)
    print(f"Input {idx+1}: {x} → Cluster {winner} (Distances: {distances})")

history = np.array(history)  # shape: (epochs+1, clusters, dimensions)
epochs = history.shape[0]
features = history.shape[2]

for cluster in range(2):
    plt.figure(figsize=(10, 4))
    for dim in range(features):
        plt.plot(range(epochs), history[:, cluster, dim], marker='o', label=f'Feature {dim+1}')
    plt.title(f'📈 Cluster {cluster} Weight Evolution Over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Weight Value')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()